### ISSUE TITLE
APKs?

### ISSUE THREAD

**Issue by PinguinoSottaceto** [sergiocastell/spotify-dogfood#16]
Hi man,
maybe it's a stupid question but...where can I find the precompiled APKs?

**Comment by Bockwurst-Mit-Puls** [comment]
Look in the readme


-------- Ursprüngliche Nachricht --------
Von: PinguinoSottaceto <notifications@github.com>
Gesendet: 26. Oktober 2017 17:01:25 MESZ
An: sergiocastell/spotify-dogfood <spotify-dogfood@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Betreff: [sergiocastell/spotify-dogfood] APKs? (#16)

Hi man,
maybe it's a stupid question but...where can I find the precompiled APKs?

**Comment by PinguinoSottaceto** [comment]
Oh
so sorry, i didn't read until the end.
i'm so stupid.
