### ISSUE TITLE
New version 8.4.26.157

### ISSUE THREAD

**Issue by Saverio7310** [sergiocastell/spotify-dogfood#17]
The new version makes the smartphone speakers to crackle. I am sure of that because I listen the same music on youtube and this problem doesn't show. I try to install the previous version but it tells the data is damaged. Pls help me.

**Comment by Saverio7310** [comment]
They crackle on the bass

**Comment by sergiocastell** [comment]
Enable volume normalisation.

**Comment by sergiocastell** [comment]
Issue closed. Supposedly fixed version is about to be rolled out.
