### ISSUE TITLE
Had to connect everytime launching app

### ISSUE THREAD

**Issue by fredfred41** [sergiocastell/spotify-dogfood#18]
Hi
Good work on this, thanks for it. Only one annoying little thing. I have to connect everytime I launch the app... I have a honor 8, emui 5.0, Android 7.0, the app is protected from closing on lockscreen. But I still have to reconnect, when I didn't use it for a while.. I m using classic email/pass connection. Any idea what the problem could be? Anyone else having the same.
Thanks

**Comment by woohooatb** [comment]
Install LineageOS.

**Comment by fredfred41** [comment]
ok.. could be a solution, but a little bit too much work...
thanks anyway...

**Comment by sergiocastell** [comment]
@fredfred41 Test on the official app and see if the issue happens there too.

**Comment by fredfred41** [comment]
Why didn't I think about it by myself, before, silly me... so, I only have to reconnect with your dogfood version, the official app work fine...
Am I really the only one?
Is there some log, I could send, or other test I could do?
Thanks

**Comment by sergiocastell** [comment]
Okay, then that's weird to hear :/ Yes, you seem to be the very first to experience it.  
However, I'm releasing an update in the following minutes, so stay tuned and try with that new one! @fredfred41

**Comment by Seluj78** [comment]
I have a Huwaei P9 lite, latest version of EMUI/Android and of Spotify-Dogfood and no trouble. Try resetting your phone entirely (factory reset)

**Comment by fredfred41** [comment]
I just installed the latest version, 8.4.27.845 , and the problem seems to be solved. I don't know if it 's the new version, or the fact that I previouly uninstalled dogfood, installed and uninstalled official, and finally install the latest dogffod version... but it looks ok. I' ll post updates.
Please don't close the thread today

Thanks

**Comment by sergiocastell** [comment]
Hi, any news @fredfred41?

**Comment by fredfred41** [comment]
yes , everything is working well, no more problems, thanks, I think you could close this.
