### ISSUE TITLE
Autoupdate feature

### ISSUE THREAD

**Issue by lokiuox** [sergiocastell/spotify-dogfood#19]
As the title says, it would be nice to have an auto-update feature for this app, maybe checking and fetching newer apks directly from github.
I don't know much about how Spotify is coded, but maybe the "a new version is available" screen that come up often in the official app could be modified to suit our needs.

**Comment by Seluj78** [comment]
@lokiuox Sergio already has an app that does that, it's a separate app that checks for a new version

It doesn't seem to work for me tho, as I tried it once but you can try it, it's on his GitHub

**Comment by sergiocastell** [comment]
Closed as there's already an app for that, Updater for Spotify: https://github.com/spotify-dogfood/updater-for-spotify
