### ISSUE TITLE
Crash/log out when set "offline mode"

### ISSUE THREAD

**Issue by Leoxur** [sergiocastell/spotify-dogfood#2]
Can you delete the "offline" item from the settings so as not to press it incorrectly?

**Comment by sergiocastell** [comment]
I can't reproduce. Please add more info and logs.

**Comment by Leoxur** [comment]
I don't know why but neither am i... Don't know what was the other time :D

**Comment by sergiocastell** [comment]
I'm going to close your issue then. If it happens again, open a new issue or re-open this one of you can.
