### ISSUE TITLE
App launches in tablet mode - UI not user friendly on playlist/album lists

### ISSUE THREAD

**Issue by qxp65** [sergiocastell/spotify-dogfood#25]
Maybe add a button in the settings to switch between phone and tablet 'mode'

**Comment by mithuns12** [comment]
Exactly!

**Comment by JingoJammer** [comment]
Pic if needed : 

![image](https://user-images.githubusercontent.com/34248410/33568955-b52557dc-d8ed-11e7-8ca9-a18a9f17da0d.png)

**Comment by sergiocastell** [comment]
Regression to version 8.4.28.967 just done.

**Comment by sergiocastell** [comment]
Closed as it was solved in version 8.4.31.723 milestone.
