### ISSUE TITLE
New UI is not user friendly and is waste of space.

### ISSUE THREAD

**Issue by mithuns12** [sergiocastell/spotify-dogfood#26]
Hard to change the sort feature, missing song information etc.
Please change it back or provide an option in settings.

**Comment by sergiocastell** [comment]
Dupe of #25. Closed.

**Comment by sergiocastell** [comment]
Issue #25 fricking disappeared from the repo (?????), so I'm reopening this one until GitHub solves it.

**Comment by sergiocastell** [comment]
Issue closed as it has reached it's milestone on version 8.4.31.723. Check it out [here](https://github.com/sergiocastell/spotify-dogfood/releases/tag/8.4.31.723).
