### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by BakasuraRCE** [sergiocastell/spotify-dogfood#3]
Hello,

I do not know if this is related to spotify and "some mechanism hidden", but after about 30 minutes of having installed the latest release of spotify-dogfood my cell phone was restored to the factory state without any confirmation.

Please do not call me "crazy" and take some time to consider this as something possible.

OS: Android 7.1.1
Cell Phone: Samsung Galaxy S4

**Comment by jleslie97** [comment]
Because you are running a more up to date version of the android OS than the s8. I'm gonna assuming your running a custom ROM. Was this applied recently before installing dogfood? Did you install other applications around the same time?

Without a log cat or more details to reproduce the bug (if it is specifically a bug within the app) there isn't much the developer can do


_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BakasuraRCE** [comment]
I understand that without error log there is not much to be done.

Unfortunately I can not give you more details because everything was erased. What I can say is that the custom ROM worked for more than 7 months without problems. And when I install spotify-dogfood everything works very well. I heard about 5 songs and then I left my phone. When I sent a text message in whatapp it was turned off and then restored to the factory state.

**Comment by jleslie97** [comment]
Any possibility that you could try to replicate the issue? Have you used the non dogfood version of Spotify on this rom. Sometimes with custom ROMs I have noticed the audio FX doesn't play nice with Spotify and can cause crashes

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sergiocastell** [comment]
Hola @BakasuraRCE, permíteme responderte en español. 

En qué custom rom te ha sucedido? Podrías volver a intentar instalar Spotify Dogfood en esa misma ROM y ver si sigue sucediendo?  

Lo que yo entiendo es que, o bien realizas un factory reset desde TWRP, o una aplicación **elevada**, como puede ser una terminal, pueden triggear un factory reset (y aún con todo y con ello TWRP pondría pegas y avisos), así que me parece bastante imposible más teniendo en cuenta que Spotify Dogfood nunca pide ni va a pedir permisos de superusuario para realizar ninguna acción (más que nada, pòrque ninguno de sus módulos lleva eso implementado).  

Marco esta incidencia como 'no reproducible' y como 'pregunta' de carácter general.

**Comment by BakasuraRCE** [comment]
I tried to reproduce the error, but did not succeed.

Thanks to everyone :-D, I close the subject.
