### ISSUE TITLE
Some part of settings isn't translated

### ISSUE THREAD

**Issue by the4anoni** [sergiocastell/spotify-dogfood#35]
I can help with translating to Polish ;)
![1514234445032](https://user-images.githubusercontent.com/13403084/34342819-78142d48-e9bc-11e7-89f8-2233bde05d5e.jpg)

**Comment by sergiocastell** [comment]
Nah, **adds won't fix tag**, I won't translate that. It's too much work for each release.

**Comment by sergiocastell** [comment]
Oh, and Merry Christmas for you too!

**Comment by the4anoni** [comment]
Thanks :)
