### ISSUE TITLE
Too many permisions

### ISSUE THREAD

**Issue by SrSands** [sergiocastell/spotify-dogfood#37]
I had a look in to the permisions app and you can turn off on and off things like the camera, the microphone, contacts.... Why are there this options? If the app doesn't use it why you can give it that permisions? It generates me mistrust...

**Comment by sergiocastell** [comment]
Why don't you rather ask Spotify for that and not me? I did not add those permissions because I wanted.

**Comment by SrSands** [comment]
Oh there are Spotify's original permisions! Sorry, muy bad and thanks for the response :)

**Comment by sergiocastell** [comment]
¡Sin problema!
