### ISSUE TITLE
Spotify New UI

### ISSUE THREAD

**Issue by ronchi130** [sergiocastell/spotify-dogfood#43]
It is possibile to force the new Spotify UI into the app via an update or it is something that you can't add because it is something activated by server? Because I would like to see the new UI.

**Comment by sergiocastell** [comment]
These are the kind of issues that trigger me. If it's not available already, it's for a reason. Serverside a/b stuff can't be triggered.

**Comment by loran2** [comment]
Just to put it out there, not to doubt your previous statement but there is a iOS tweak that enables the new UI which is usually specific to certain playlists to all songs. aptly named "SpotifyNewUIEnabler!"
