### ISSUE TITLE
Premium Features?

### ISSUE THREAD

**Issue by nathanjace** [sergiocastell/spotify-dogfood#47]
All the premium features are now disabled. It's made on purpose with the new update or...?

**Comment by SuperShifty** [comment]
having the same problem as well.

**Comment by hg8** [comment]
> Hello everyone, today is announcements day!
> 
> In order to comply with XDA's Rules and CoC, Spotify Dogfood has taken a new direction, and now offers *exclusively* Ad-free music playback. Any other features won't be included anymore in this mod. But, that doesn't mean anything if you're a true, a core user of this app, because there will still be regular updates to it, as there has been up until now.
> 
> However, all patchsets, branches and everything that has been posted up until now will be deleted progressively, in order to comply with the above mentioned.
> 
> Still, I'm pleased to announce Spotify Dogfood 8.4.37.571! Just as always, you can find the new PatchSet in the GitHub repo, as well as binaries in the Releases section. Also, remember you can always keep up-to-date with Updater for Spotify, which you can get from here.
> 

https://forum.xda-developers.com/showpost.php?p=75214194&postcount=807

**Comment by ronchi130** [comment]
Why just why? You ruined an app that was working Just fine. I am really disappointed.

**Comment by spikespaz** [comment]
Why do you care about having the app on XDA? Just keep it here, in GitHub, so that the app remains useable to people who want premium features.

**Comment by ronchi130** [comment]
Why ditch a such beautiful project?! It was a very good idea to make obsolete those apps full of viruses that you found on those sites. I know that I should pay for a service but I think that if the Spotify is free on desktop it should be free even on mobile. I'm staying with the older version until we have a new update.

**Comment by SuperShifty** [comment]
Well... For everyone else, until things go back to normal (fingers crossed) a temp fix for root users is downloading Lucky Patcher and using the custom patch on Dogfood. It said the patch failed but I'm now able to select songs again at least.

**Comment by cheeseman1997** [comment]
Is there anyone, who has all the previous patches? Besides I don't think that Dogfood will be the same, it is evenproved to be true by an XDA moderator. Rest in Peace Spotify Dogfood. You were the greatest mod ever!

**Comment by fredfred41** [comment]
Hi, so sad to read that... wich version still have premium features? where can I download it? thanks

**Comment by sergiocastell** [comment]
Hello @nathanjace, @SuperShifty, @hg8, @ronchi130, @spikespaz, @cheeseman1997, @fredfred41.

This is not the end. And I invite you to join our [Telegram Group](https://t.me/spotifydogfood) in order to discover what's next.

**Comment by duttaditya18** [comment]
@sergiocastell Where can we get the source code of Spotify Dogfood Core? Or is it not Open Source?

**Comment by sergiocastell** [comment]
@duttaditya18 Those questions will not be answered here, but in our Telegram group instead: t.me/spotifydogfood (click on the Support group link to join)

**Comment by duttaditya18** [comment]
@sergiocastell All right! Sorry!
