### ISSUE TITLE
All "Dogfood" feature are gone with latest Update

### ISSUE THREAD

**Issue by Vikijaka** [sergiocastell/spotify-dogfood#48]
Hi there,

im sorry to open this Issue, but did Dogfood "died" with your latest Update?
Can't find any "readme" or something else which notes that "all" feature of this 
OpenSource Spotify Mod are gone, except for Ads(Audio/Visuell).

personally i have never had any audio-ads with the Official App.

Or am i occuring a "bug" which don't let me play some Song in order except for "just shuffle"?

Greetings

**Comment by sergiocastell** [comment]
Hello @Vikijaka. 

This is not the end. And I invite you to join our Telegram Group in order to discover what's next.
You can also drop me an email to iamlinuxct@linuxct.info.
