### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by richfreestone** [sergiocastell/spotify-dogfood#5]
I'm not sure if this is supposed to happen, but Android Auto isn't picking up Spotify Dogfood as a music player - is this intentional?

**Comment by sergiocastell** [comment]
As already explained in XDA-Developers thread:  

> This application won't work with Android Auto, since it hasn't been installed by the Google Play Store's agent. Fortunately, there's a fix found by XDA's News Writer @MishaalRahman, which you can read [here](https://www.xda-developers.com/psa-spotify-and-other-apps-not-working-with-android-auto-heres-a-fix/).  

Hope this helps.
