### ISSUE TITLE
Can't change music quality

### ISSUE THREAD

**Issue by MrKaiju** [sergiocastell/spotify-dogfood#51]
Hi, with the new version of Spotify Dogfood (8.4.37.571) I can't change the music quality and I don't know why

EDIT: It's not only the music quality, now Dogfood works only with shuffle, like the normal Spotify

**Comment by vidrafeed** [comment]
Me too since I installed the latest update

**Comment by sergiocastell** [comment]
Please see https://github.com/sergiocastell/spotify-dogfood/issues/47#issuecomment-358120437
