### ISSUE TITLE
Unlimited song skipping not working on Spotify Dogfood 8.4.37.571

### ISSUE THREAD

**Issue by NotMyBusiness** [sergiocastell/spotify-dogfood#52]
Hello Sergio!

I updated my spotify dogfood to the last version (8.4.37.571) yesterday and since then I cannot skip songs without limit or choose the minute of the song I want to play. I have no problem with ads, they haven't appeared. I tried deleting data and reinstalling it from fresh but doesn't work either. I've installed the previous version for now and everything is perfect. If you need more info (logs, screenshots, whatever), tell me and I'll try to do it as fast as I can. 

You're doing an amazing job, really appreciate your work!

Kind regards.

**Comment by Rex109** [comment]
Same here! I tried everything, even with 2 different phones, nothing works. With the previous one is all ok.

**Comment by sergiocastell** [comment]
Hi @NotMyBusiness, @Rex109,

Please see https://github.com/sergiocastell/spotify-dogfood/issues/47#issuecomment-358120437

**Comment by NotMyBusiness** [comment]
Hi @sergiocastell and sorry for not viewing that thread before opening a new one. Thanks again!

**Comment by Rex109** [comment]
@sergiocastell Oh ok, i'm a little bit disappointed but... okay... that's fine
