### ISSUE TITLE
Latest release dont work

### ISSUE THREAD

**Issue by the4anoni** [sergiocastell/spotify-dogfood#53]
Tested on both devices with arm and with arm64. How can i dl old release (i see only this newest)

**Comment by sergiocastell** [comment]
Hi @the4anoni,

Please see https://github.com/sergiocastell/spotify-dogfood/issues/47#issuecomment-358120437

**Comment by the4anoni** [comment]
:(

**Comment by the4anoni** [comment]
Going back to closed source mods

**Comment by sergiocastell** [comment]
@the4anoni Did you even bother to read the message? Mail me at iamlinuxct@linuxct.info
