### ISSUE TITLE
Acts like I have a normal account on latest update

### ISSUE THREAD

**Issue by NewbieGamingYT** [sergiocastell/spotify-dogfood#54]
I click on any song makes me shuffle play, ads, no going backwards. Lost all features. Please fix, I love this app! Since this one isn't working, here is a link to one which is: Link removed by linuxct

I tested this one and it works!!

**Comment by BloodShura** [comment]
Indeed; latest version, **8.4.37.571**, seems to be broken. Nevertheless, **8.4.36.305** still works fine.

**Comment by EvaristoLopez** [comment]
It happens the same to me

**Comment by NewbieGamingYT** [comment]
https://www.mediafire.com/download/uju0d2vz98j3i45

Here is the official latest works from Sergio himself via Telegram!

**Comment by teochaves** [comment]
is it possible to listen offline?

**Comment by NewbieGamingYT** [comment]
Nope!

**Comment by sergiocastell** [comment]
@NewbieGamingYT Did you understand the part of not redistributing the APK outside the group? May you please delete it from Mediafire? Thanks

**Comment by sergiocastell** [comment]
If anyone is interested on a new version, you should check out our [Telegram Group](t.me/spotifydogfood)
