### ISSUE TITLE
Not working properly 

### ISSUE THREAD

**Issue by tkosamja** [sergiocastell/spotify-dogfood#55]
When I install spotify-dogfood apk from the releases, I get a different UI than most people and I can only hear the select music in some playlists. 

This is the UI I'm getting:
![photo_2018-01-20_09-48-11](https://user-images.githubusercontent.com/26143003/35182211-1ac0c1fe-fdc8-11e7-9619-572447984e54.jpg)
![photo_2018-01-20_09-47-58](https://user-images.githubusercontent.com/26143003/35182212-1adee1b6-fdc8-11e7-9692-d69098c739de.jpg)

**Comment by tkosamja** [comment]
Also happens in old UI since update

**Comment by tkosamja** [comment]
Also happens in old UI since update

**Comment by cheeseman1997** [comment]
You get the new UI, because you (may) live in the US and your phone is in the US, or at least according to its imei. And that's why the new ui is triggered. Unfortunatelly every premium feature will not be avaible in any further version of Spotify Dogfood, but ad free.

**Comment by tkosamja** [comment]
Never mind, I got it
My mistake, you can close this.

**Comment by cheeseman1997** [comment]
@sergiocastell If you would, please lock it.

**Comment by sergiocastell** [comment]
References #47.
