### ISSUE TITLE
Simply saying I don't have premium

### ISSUE THREAD

**Issue by JorgeMew** [sergiocastell/spotify-dogfood#59]
I installed it as a normal apk , I never had spotify on this phone before , but my account is old though.

What Should I do?

**Comment by SharkEzz** [comment]
Same problem for me. Can not play a particular music in the latest version, it works just by pressing the button to play a random music from a playlist.

**Comment by PoorPocketsMcNewHold** [comment]
#47

> Hello everyone, today is announcements day!
> 
> In order to comply with XDA's Rules and CoC, Spotify Dogfood has taken a new direction, and now offers exclusively Ad-free music playback. Any other features won't be included anymore in this mod. But, that doesn't mean anything if you're a true, a core user of this app, because there will still be regular updates to it, as there has been up until now.
> 
> However, all patchsets, branches and everything that has been posted up until now will be deleted progressively, in order to comply with the above mentioned.
> 
> Still, I'm pleased to announce Spotify Dogfood 8.4.37.571! Just as always, you can find the new PatchSet in the GitHub repo, as well as binaries in the Releases section. Also, remember you can always keep up-to-date with Updater for Spotify, which you can get from here.

[https://forum.xda-developers.com/showpost.php?p=75214194&postcount=807](https://forum.xda-developers.com/showpost.php?p=75214194&postcount=807)

**Comment by JingoJammer** [comment]
Well that is a bummer....

**Comment by hg8** [comment]
Please read https://github.com/sergiocastell/spotify-dogfood/issues/47#issuecomment-358120437
