### ISSUE TITLE
App not working correctly

### ISSUE THREAD

**Issue by guayo23** [sergiocastell/spotify-dogfood#63]
Since the last 2 updates the app doesn't work correctly, it is like if I had the normal free version of the Play Store (I have adds, only shuffle button...) I don't know why, but I tried an older version and it worked, but I want the new versions :(

**Comment by deklesen** [comment]
Same here. Device: Nexus 6P, Android: 8.1.0, no root, newest version of Spotify Dogfood..

**Comment by guayo23** [comment]
At least you have Android Oreo 😢 I'm still waiting for it on my S7

**Comment by deklesen** [comment]
Solution to the problem:
There are now two versions of Spotify Dogfood: the normale one and Spotify Dogfood Core. Check the Telegram channel for further information.

**Comment by guayo23** [comment]
Oh ok, I got it, now there's the CORE version.
Thanks
