### ISSUE TITLE
Skips are limited

### ISSUE THREAD

**Issue by nefarious77** [sergiocastell/spotify-dogfood#66]
Skips are limited on 571 & 612. After a few skips I get asked to upgrade to premium. I am logged in. I thought skips were unlimited on older versions.

**Comment by d4rkf0x** [comment]
They were, seems to be a new problem.

**Comment by creeratsea** [comment]
I have same issue on both versions. And it forces me to shuffle play.

**Comment by Jassun16** [comment]
skips are limited and also only shuffle works. We couldn't play whatever song we like and the songs are greyed out. Asks to become Premium member.

**Comment by bd94** [comment]
Running 612 I am also having this problem. Can only skip a limited amount and can only suffle play.

**Comment by XWhatevs** [comment]
Apparently it's on purpose. Bullshit, uninstalled.

**Comment by hg8** [comment]
Just read before complaining people.... https://github.com/sergiocastell/spotify-dogfood/issues/47#issuecomment-358120437
