### ISSUE TITLE
New version available prompt and offline mode

### ISSUE THREAD

**Issue by Seluj78** [sergiocastell/spotify-dogfood#8]
Hi !

I've just came across your Spotify mod and it's really amazing ! (Me and my girlfriend love the paw on the logo ;) )

I came across the "New version available" prompt randomly while browsing the app which is really annoying and I thought you might be able to do something

And about the offline mode, I don't know if it is possible to do something to it but if you can, then that'd be amazing !

Anyway, keep up the good work 😘

**Comment by WtfJoke** [comment]
> And about the offline mode, I don't know if it is possible to do something to it but if you can, then that'd be amazing !

He stated in his [xda-thread](https://forum.xda-developers.com/android/apps-games/mod-spotify-dogfood-ad-free-spotify-t3632423) that he wont do this, and dont want to be asked about it.

> As commented by Senior Moderator @matt4321, please, refrain from asking for other premium features to be unlocked.

**Comment by Seluj78** [comment]
I'm sorry my bad, I won't do it :)

**Comment by sergiocastell** [comment]
Issue closed as the [new update](https://github.com/sergiocastell/spotify-dogfood/releases/tag/8.4.21.495) fixes this behaviour.
